services:
  nginx:
    image: nginx:alpine
    container_name: nginx-eapik-perencanaan
    restart: unless-stopped
    tty: true
    ports:
      - "8100:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/app:delegated
    depends_on:
      - php
    networks:
      - eapik-perencanaan
  
  db:
    image: mysql:8.0
    container_name: mysql-eapik-perencanaan
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: strong_password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - eapik-perencanaan

  php:
    build:
      args:
        user: fuad
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php-eapik-perencanaan
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - ./src:/var/www/app:delegated
    networks:
      - eapik-perencanaan

networks:
  eapik-perencanaan:
    driver: bridge